services:
  poc-db:
    image: postgres:17.4
    hostname: db-postgresql
    container_name: db-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: db-postgresql
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5532:5432"
    networks:
      - local-des

networks:
  local-des: