spring:
    flyway:
        enabled: true
        clean-disabled: false
        locations: classpath:db/migration

    datasource:
        url: jdbc:postgresql://localhost:5532/db-postgresql
        driverClassName: org.postgresql.Driver
        username: admin
        password: admin